spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/finance
    username: postgres
    password: 123456
    hikari:
      maximum-pool-size: 50
      connection-timeout: 3000
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        ddl-auto: validate
        jdbc:
          batch_size: 50
        order_inserts: true
        default_batch_fetch_size: 50

    open-in-view: false

  flyway:
    locations: classpath:db/migration
    encoding: UTF-8
    baseline-on-migrate: false

# ngưỡng cảnh báo của ServicePerformanceAspect (chỉ chạy ở profile dev)
app:
  perf:
    sql-warn-threshold: 10
    slow-ms: 300

logging:
  level:
    com.datn.financeapp: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    org.springframework.transaction: DEBUG