server:
  servlet:
    context-path: ${PATH}

spring:
  profiles:
    active: ${PROFILES_ACTIVE}
  application:
    name: financeapp
  jackson:
    property-naming-strategy: SNAKE_CASE

  mail:
    host: ${MAIL_HOST:}
    port: ${MAIL_PORT:}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

app:
  mail:
    from: ${MAIL_FROM:${MAIL_USERNAME:}}

google:
  web-client-id: ${GOOGLE_WEB_CLIENT_ID:}

jwt:
  secret: ${JWT_SECRET}
  access-token-expiry-seconds: 3600
  refresh-token-expiry-days: 30

rate-limit:
  max-request-email-forgot-password: 5
  reset-request-email-forgot-password: 1h